[default.extend-words]
colour = "British English"
favourite = "British English"
honour = "British English"
organise = "British English"
organised = "British English"
organising = "British English"
organisation = "British English"
analyse = "British English"
realise = "British English"
realised = "British English"
realising = "British English"
licence = "British English"
defence = "British English"
offence = "British English"
centre = "British English"
theatre = "British English"
metre = "British English"
litre = "British English"
travelling = "British English"
cancelled = "British English"
labour = "British English"
neighbour = "British English"
behaviour = "British English"
rumour = "British English"
cheque = "British English"
grey = "British English"
aeroplane = "British English"
storey = "British English"
tyre = "British English"
dialogue = "British English"
catalogue = "British English"
programme = "British English"
plough = "British English"
jewellery = "British English"
aluminium = "British English"

[files]
extend-exclude = ["*.md", "*.rst", "docs/**", "**/README*", "**/CHANGELOG*", "**/LICENSE*"]

