[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = "hrsh7th/cmp-path"

[[plugins]]
repo = "hrsh7th/cmp-buffer"

[[plugins]]
repo = "hrsh7th/cmp-cmdline"

[[plugins]]
repo = "saadparwaiz1/cmp_luasnip"

[[plugins]]
repo = "L3MON4D3/LuaSnip"

[[plugins]]
repo = "rafamadriz/friendly-snippets"

