[[plugins]]
repo = "nvim-treesitter/nvim-treesitter-textobjects"
repo = "windwp/nvim-ts-autotag"

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
build = ":TSUpdate"
depends = [
  "nvim-treesitter/nvim-treesitter-textobjects",
  "windwp/nvim-ts-autotag"
]
nhook_add = '''
  lua require("plugins.nvim-treesitter)
'''

