[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"
repo = "hrsh7th/cmp-path"
repo =  "hrsh7th/cmp-buffer"
repo =  "hrsh7th/cmp-cmdline"
repo =  "saadparwaiz1/cmp_luasnip"
repo =  "L3MON4D3/LuaSnip"

[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = [
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-cmdline",
  "saadparwaiz1/cmp_luasnip",
  "L3MON4D3/LuaSnip",
  "rafamadriz/friendly-snippets"
]
hook_add = '''
  lua require("plugins.nvim-cmp")
'''

