# Rule
Rule=default
# Punctuation Style
PunctuationStyle=Japanese
# Initial Input Mode
InitialInputMode=Hiragana
# Page size
PageSize=10
# Candidate Layout
Candidate Layout=Vertical
# Return-key does not insert new line on commit
EggLikeNewLine=True
# Show Annotation
ShowAnnotation=True
# Candidate Key
CandidateChooseKey="Qwerty Center Row (a,s,d,...)"
# Number candidate of Triggers To Show Candidate Window
NTriggersToShowCandWin=0

[CandidatesPageUpKey]
0=Page_Up

[CandidatesPageDownKey]
0=Next

[CursorUp]
0=Up

[CursorDown]
0=Down


[Dictionary]
0=Dict
1=Dict
2=Dict
3=Dict
4=Dict
5=Dict
6=Dict

[Dictionary/0]
# File
File="~/.config/skkeleton/SKK-JISYO.user"
# Mode
Mode=User

[Dictionary/1]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.L.utf8"
# Mode
Mode=System

[Dictionary/2]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.geo.utf8"
# Mode
Mode=System

[Dictionary/3]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.itaiji.utf8"
# Mode
Mode=System

[Dictionary/4]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.jinmei.utf8"
# Mode
Mode=System

[Dictionary/5]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.propernoun.utf8"
# Mode
Mode=System

[Dictionary/6]
# File
File="~/.config/skkeleton/dicts/SKK-JISYO.station.utf8"
# Mode
Mode=System
